import type { QuestionItem } from '../types/questions';

const forbiddenInQuestionUI = [
  /\bNe\b/, /\bNi\b/, /\bSe\b/, /\bSi\b/, /\bTe\b/, /\bTi\b/, /\bFe\b/, /\bFi\b/,
  /Model A/i, /PoLR/i, /suggestive/i, /mobilizing/i, /quadra/i, /valued/i, /unvalued/i,
  /producer/i, /threat/i, /receiver/i, /Seeded ID/i, /itemId/i
];

const forbiddenInPublic = [/ChatGPT/i, /OpenAI/i, /Gemini/i, /generated by AI/i, /dibuat oleh AI/i, /powered by AI/i, /\bdemo\b/i, /\bsample\b/i, /prototype/i, /playground/i];

function inspectText(text: string, rules: RegExp[], label: string, id: string, errors: string[]) {
  for (const rule of rules) {
    if (rule.test(text)) errors.push(`${label} leak in ${id}: ${rule}`);
  }
}

export function auditQuestionLanguage(items: QuestionItem[]): string[] {
  const errors: string[] = [];
  for (const item of items) {
    inspectText(item.statementCasual, forbiddenInQuestionUI, 'question', item.id, errors);
    inspectText(item.statementCasual, forbiddenInPublic, 'public', item.id, errors);
    for (const option of item.options) {
      inspectText(option.label, forbiddenInQuestionUI, 'option label', item.id, errors);
      inspectText(option.meaning, forbiddenInQuestionUI, 'option meaning', item.id, errors);
      inspectText(option.reaction, forbiddenInQuestionUI, 'option reaction', item.id, errors);
      inspectText(option.label, forbiddenInPublic, 'option public', item.id, errors);
    }
  }
  return errors;
}
